services:
  gateway:
    image: nginx:alpine
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service-1.nginx:/etc/nginx/sites-enabled/service-1:ro
      - ./service-2.nginx:/etc/nginx/sites-enabled/service-2:ro
    networks:
      - lab2-net

networks:
  lab2-net:
    external: true
