services:
  service-2:
    container_name: service-2
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm run start"
    env_file:
      - ../.env
    ports:
      - "3001:3001"
    networks:
      - lab2-net
    environment:
      - APP_PORT=3001

networks:
  lab2-net:
    external: true
