services:
  mqlistener:
    container_name: mqlistener
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm run start"
    env_file:
      - ../.env
    networks:
      - lab2-net

networks:
  lab2-net:
    external: true
